export enum Method {
    CreateERC20 = "CREATE_ERC20",
    CreateDao = "CREATE_DAO",
    // DAO events
    DAO_SUBMIT = "DAO_SUBMIT",
    DAO_APPROVE = "DAO_APPROVE",
    DAO_REVOKE = "DAO_REVOKE",
    DAO_EXECUTE = "DAO_EXECUTE",
    DAO_METADATA_UPDATED = "DAO_METADATA_UPDATED",
    // ERC20 events
    ERC20_TRANSFER = "ERC20_TRANSFER",
    ERC20_APPROVAL = "ERC20_APPROVAL"
}